name: gitrob
version: '1.0'
summary: Reconnaissance tool for GitHub organizations 
description: |
  Gitrob is a tool to help find potentially sensitive files pushed to public 
  repositories on Github. Gitrob will clone repositories belonging to a user 
  or organization down to a configurable depth and iterate through the commit 
  history and flag files that match signatures for potentially sensitive 
  files. The findings will be presented through a web interface for easy 
  browsing and analysis. 
grade: stable
confinement: strict
base: core18
parts:
  gitrob:
    plugin: go
    source: https://github.com/michenriksen/gitrob.git
    go-importpath: github.com/michenriksen/gitrob
    build-packages:
      - build-essential
apps:
  gitrob:
    command: bin/gitrob
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - home
      - network
      - network-bind
